# Generated by Django 3.2 on 2021-04-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_u', models.CharField(default='', max_length=8, unique=True)),
                ('the_host', models.CharField(max_length=50, unique=True)),
                ('the_guest_pause', models.BooleanField(default=False)),
                ('votes_skip', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
